<?php

function csas_dvl_ob($vars = array(), $filename = '', $rel_path = 'sites/default/files/tmp/') {
  ob_start();
  print_r($vars);
  $plain = ob_get_contents();
  ob_end_clean();

  if ($handle = fopen($_SERVER['DOCUMENT_ROOT'] . base_path() . $rel_path . "temp_" . $filename . "_" . microtime() . ".txt", 'w+')) {
    fwrite($handle, $plain . "\n");
    fclose($handle);
  }
}

function _csas_dvl_is_lcl_dmn() {
  global $base_url;
  $ret = FALSE;
  $base_url_prs = parse_url($base_url);
  if (!empty($base_url_prs['host']) && ($hst_ex = explode('.', $base_url_prs['host']))) {
    $frs_dmn = array_pop($hst_ex);
    if ($frs_dmn == 'sas') {
      $ret = TRUE;
    }
  }
  return $ret;
}

/**
 * Implementation of hook_menu().
 */
function csas_dvl_menu() {
  $items['admin/config/content/csas_dvl'] = array(
    'title' => 'Csas dvl',
    'description' => 'Csas dvl',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('csas_dvl_admin_config_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'csas_dvl.admin.inc',
  );
  return $items;
}

function csas_dvl_preprocess_page(&$vars){
  global $user;
  if($user->uid == 1 && variable_get('csas_dvl_dev_mode', FALSE)){
    drupal_add_js(drupal_get_path('module', 'csas_dvl') . '/csas_dvl.js');
  }
}